### PR TITLE
Add camkes-vm-images required by Arm vm examples

### PR DESCRIPTION
**Pull request by oliver-wm**
Fixes Issue https://github.com/seL4/camkes-vm-examples-manifest/issues/3

### CODE REVIEW

**Comment by oliver-wm** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit abde9d18038b88e43d9df5873ace0a260b00573f

### Summary

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - camkes-vm-examples-manifest - EXT-seL4-add-camkes-images-4 | SUCCESSFUL |
| Code Quality - Reuse License Check - camkes-vm-examples-manifest - EXT-seL4-add-camkes-images-4 | SUCCESSFUL |
| Code Quality - Signed-off-by - camkes-vm-examples-manifest - EXT-seL4-add-camkes-images-4 | FAILED |
| Code Quality - Style - camkes-vm-examples-manifest - EXT-seL4-add-camkes-images-4 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Signed-off-by - camkes-vm-examples-manifest - EXT-seL4-add-camkes-images-4 | Check all commits have been Signed-Off-by | 1 of 1 job failed |

**Job: signedoff**
Build logs

    02-Mar-2021 17:22:53	Build Code Quality - Signed-off-by - camkes-vm-examples-manifest - EXT-seL4-add-camkes-images-4 - signedoff #1 (CQ-CAMKESVMEXAMPLESMANIFESTSIGNEDOFF0-CAMKESVMEXAMPLESMANIFESTSIGNEDOFFSIGNEDOFF-1) started building on agent A local agent 2, bamboo version: 7.1.4
    02-Mar-2021 17:22:53	I run on the Bamboo server!
    02-Mar-2021 17:22:53	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESVMEXAMPLESMANIFESTSIGNEDOFF0-CAMKESVMEXAMPLESMANIFESTSIGNEDOFFSIGNEDOFF
    02-Mar-2021 17:22:54	Executing build Code Quality - Signed-off-by - camkes-vm-examples-manifest - EXT-seL4-add-camkes-images-4 - signedoff #1 (CQ-CAMKESVMEXAMPLESMANIFESTSIGNEDOFF0-CAMKESVMEXAMPLESMANIFESTSIGNEDOFFSIGNEDOFF-1)
    02-Mar-2021 17:22:54	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESVMEXAMPLESMANIFESTSIGNEDOFF0-CAMKESVMEXAMPLESMANIFESTSIGNEDOFFSIGNEDOFF/. (location: .)
    02-Mar-2021 17:22:54	Artifact 'code' prepared in 19.71 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESVMEXAMPLESMANIFESTSIGNEDOFF0-CAMKESVMEXAMPLESMANIFESTSIGNEDOFFSIGNEDOFF/./code.tar.gz
    02-Mar-2021 17:22:54	Running pre-build action: VCS Version Collector
    02-Mar-2021 17:22:54	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    02-Mar-2021 17:22:54	+ tar xf code.tar.gz --recursive-unlink
    02-Mar-2021 17:22:54	Finished task 'Untar code' with result: Success
    02-Mar-2021 17:22:54	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    02-Mar-2021 17:22:54	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESVMEXAMPLESMANIFESTSIGNEDOFF0-CAMKESVMEXAMPLESMANIFESTSIGNEDOFFSIGNEDOFF
    02-Mar-2021 17:22:54	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    02-Mar-2021 17:22:54	Starting task 'Check commits have been signed-off' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    02-Mar-2021 17:22:54	+ cd camkes-vm-examples-manifest
    02-Mar-2021 17:22:54	+++ git merge-base abde9d18038b88e43d9df5873ace0a260b00573f 725a2e4554bf9ba99e12adb1c77c3665d60d70fd
    02-Mar-2021 17:22:54	++ git rev-list --invert-grep --grep=Signed-off-by: 725a2e4554bf9ba99e12adb1c77c3665d60d70fd..abde9d18038b88e43d9df5873ace0a260b00573f
    02-Mar-2021 17:22:54	+ commits_not_signed_off=abde9d18038b88e43d9df5873ace0a260b00573f
    02-Mar-2021 17:22:54	+ '[' '!' -z abde9d18038b88e43d9df5873ace0a260b00573f ']'
    02-Mar-2021 17:22:54	+ echo 'The follow commits need to be signed off:'
    02-Mar-2021 17:22:54	+ echo abde9d18038b88e43d9df5873ace0a260b00573f
    02-Mar-2021 17:22:54	+ exit 1
    02-Mar-2021 17:22:54	The follow commits need to be signed off:
    02-Mar-2021 17:22:54	abde9d18038b88e43d9df5873ace0a260b00573f
    02-Mar-2021 17:22:54	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-CAMKESVMEXAMPLESMANIFESTSIGNEDOFF0-CAMKESVMEXAMPLESMANIFESTSIGNEDOFFSIGNEDOFF-1-ScriptBuildTask-4545073016979644818.sh] was 1 while expected 0
    02-Mar-2021 17:22:54	Finished task 'Check commits have been signed-off' with result: Failed
    02-Mar-2021 17:22:54	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    02-Mar-2021 17:22:54	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESVMEXAMPLESMANIFESTSIGNEDOFF0-CAMKESVMEXAMPLESMANIFESTSIGNEDOFFSIGNEDOFF
    02-Mar-2021 17:22:54	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    02-Mar-2021 17:22:54	Starting task 'Run dco code insights' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    02-Mar-2021 17:22:54	+ cd camkes-vm-examples-manifest
    02-Mar-2021 17:22:54	++ echo ssh://git@bitbucket.ts.data61.csiro.au:7999/sel4/camkes-vm-examples-manifest.git
    02-Mar-2021 17:22:54	++ cut -d/ -f4
    02-Mar-2021 17:22:54	+ bb_proj=sel4
    02-Mar-2021 17:22:54	+ /scripts/bb_code_insights/create_code_insights.sh git-commits-signed-off sel4 camkes-vm-examples-manifest
    02-Mar-2021 17:22:54	++ dirname /scripts/bb_code_insights/create_code_insights.sh
    02-Mar-2021 17:22:54	+ SCRIPT_DIR=/scripts/bb_code_insights
    02-Mar-2021 17:22:54	+ BBS_URL=https://bitbucket.ts.data61.csiro.au
    02-Mar-2021 17:22:54	+ BBS_PROJECT=sel4
    02-Mar-2021 17:22:54	+ BBS_REPO=camkes-vm-examples-manifest
    02-Mar-2021 17:22:54	+ REPORT_TO_RUN=git-commits-signed-off
    02-Mar-2021 17:22:54	++ git rev-parse HEAD
    02-Mar-2021 17:22:54	+ COMMIT_ID=abde9d18038b88e43d9df5873ace0a260b00573f
    02-Mar-2021 17:22:54	+ REPORT_KEY=git-commits-signed-off.report
    02-Mar-2021 17:22:54	+ set +x
    02-Mar-2021 17:22:54	+ report_file=git-commits-signed-off_report.json
    02-Mar-2021 17:22:54	+ annotations_file=git-commits-signed-off_annotations.json
    02-Mar-2021 17:22:54	+ rm -f git-commits-signed-off_report.json git-commits-signed-off_annotations.json
    02-Mar-2021 17:22:54	+ /scripts/bb_code_insights/git-commits-signed-off
    02-Mar-2021 17:22:54	Running: git merge-base abde9d18038b88e43d9df5873ace0a260b00573f 725a2e4554bf9ba99e12adb1c77c3665d60d70fd
    02-Mar-2021 17:22:54	725a2e4554bf9ba99e12adb1c77c3665d60d70fd
    02-Mar-2021 17:22:54	Running: git rev-list --invert-grep --grep=Signed-off-by: 725a2e4554bf9ba99e12adb1c77c3665d60d70fd..abde9d18038b88e43d9df5873ace0a260b00573f
    02-Mar-2021 17:22:54	abde9d18038b88e43d9df5873ace0a260b00573f
    02-Mar-2021 17:22:54	Identified bad commits:
    02-Mar-2021 17:22:54	[]
    02-Mar-2021 17:22:54	+ echo 'Reporting the results to BitBucket, but doing so *secretly*, so people don'\''t see the access token'
    02-Mar-2021 17:22:54	Reporting the results to BitBucket, but doing so *secretly*, so people don't see the access token
    02-Mar-2021 17:22:54	+ set +x
    02-Mar-2021 17:22:54	+ '[' -f git-commits-signed-off_report.json ']'
    02-Mar-2021 17:22:54	+ cat git-commits-signed-off_report.json
    02-Mar-2021 17:22:54	+ '[' -f git-commits-signed-off_annotations.json ']'
    02-Mar-2021 17:22:54	{"data":[{"title":"Total number of commits not signed-off","value":0,"type":"NUMBER"}],"createdDate":1614666174284,"details":"All good B-)","key":"git-commits-signed-off.report","result":"PASS","title":"Signed-off commits"}{"title": "Signed-off commits", "data": [{"title": "Total number of commits not signed-off", "value": 0, "type": "NUMBER"}], "details": "All good B-)", "result": "PASS"}
    02-Mar-2021 17:22:54	Finished task 'Run dco code insights' with result: Success
    02-Mar-2021 17:22:54	Running post build plugin 'NCover Results Collector'
    02-Mar-2021 17:22:54	Running post build plugin 'Artifact Copier'
    02-Mar-2021 17:22:54	Running post build plugin 'npm Cache Cleanup'
    02-Mar-2021 17:22:54	Running post build plugin 'Clover Results Collector'
    02-Mar-2021 17:22:54	Running post build plugin 'Docker Container Cleanup'
    02-Mar-2021 17:22:54	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESVMEXAMPLESMANIFESTSIGNEDOFF0-CAMKESVMEXAMPLESMANIFESTSIGNEDOFFSIGNEDOFF'
    02-Mar-2021 17:22:54	Finalising the build...
    02-Mar-2021 17:22:54	Stopping timer.
    02-Mar-2021 17:22:54	Build CQ-CAMKESVMEXAMPLESMANIFESTSIGNEDOFF0-CAMKESVMEXAMPLESMANIFESTSIGNEDOFFSIGNEDOFF-1 completed.
    02-Mar-2021 17:22:54	Running on server: post build plugin 'NCover Results Collector'
    02-Mar-2021 17:22:54	Running on server: post build plugin 'Build Hanging Detection Configuration'
    02-Mar-2021 17:22:54	Running on server: post build plugin 'Clover Delta Calculator'
    02-Mar-2021 17:22:54	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    02-Mar-2021 17:22:54	All post build plugins have finished
    02-Mar-2021 17:22:54	Generating build results summary...
    02-Mar-2021 17:22:54	Saving build results to disk...
    02-Mar-2021 17:22:54	Store variable context...
    02-Mar-2021 17:22:54	Indexing build results...
    02-Mar-2021 17:22:54	Finished building CQ-CAMKESVMEXAMPLESMANIFESTSIGNEDOFF0-CAMKESVMEXAMPLESMANIFESTSIGNEDOFFSIGNEDOFF-1.


| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - camkes-vm-examples-manifest - EXT-seL4-add-camkes-images-4 | Style check on changed files | 1 of 3 jobs failed |

**Job: gitlint**
Build logs

    02-Mar-2021 17:22:54	Build Code Quality - Style - camkes-vm-examples-manifest - EXT-seL4-add-camkes-images-4 - gitlint #1 (CQ-CAMKESVMEXAMPLESMANIFESTSTYLE12-CAMKESVMEXAMPLESMANIFESTGITLINTPR-1) started building on agent A local agent 2, bamboo version: 7.1.4
    02-Mar-2021 17:22:54	I run on the Bamboo server!
    02-Mar-2021 17:22:54	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESVMEXAMPLESMANIFESTSTYLE12-CAMKESVMEXAMPLESMANIFESTGITLINTPR
    02-Mar-2021 17:22:54	Executing build Code Quality - Style - camkes-vm-examples-manifest - EXT-seL4-add-camkes-images-4 - gitlint #1 (CQ-CAMKESVMEXAMPLESMANIFESTSTYLE12-CAMKESVMEXAMPLESMANIFESTGITLINTPR-1)
    02-Mar-2021 17:22:54	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESVMEXAMPLESMANIFESTSTYLE12-CAMKESVMEXAMPLESMANIFESTGITLINTPR/. (location: .)
    02-Mar-2021 17:22:54	Artifact 'code' prepared in 12.18 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESVMEXAMPLESMANIFESTSTYLE12-CAMKESVMEXAMPLESMANIFESTGITLINTPR/./code.tar.gz
    02-Mar-2021 17:22:54	Running pre-build action: VCS Version Collector
    02-Mar-2021 17:22:54	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    02-Mar-2021 17:22:54	+ tar xf code.tar.gz --recursive-unlink
    02-Mar-2021 17:22:54	Finished task 'Untar code' with result: Success
    02-Mar-2021 17:22:54	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    02-Mar-2021 17:22:54	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESVMEXAMPLESMANIFESTSTYLE12-CAMKESVMEXAMPLESMANIFESTGITLINTPR
    02-Mar-2021 17:22:54	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    02-Mar-2021 17:22:54	Starting task 'Lint commit messages' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    02-Mar-2021 17:22:54	+ cd camkes-vm-examples-manifest
    02-Mar-2021 17:22:54	+ '[' -f .gitlint ']'
    02-Mar-2021 17:22:54	+ CONFIG=/var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESVMEXAMPLESMANIFESTSTYLE12-CAMKESVMEXAMPLESMANIFESTGITLINTPR/standard_seL4_tools/misc/.gitlint
    02-Mar-2021 17:22:54	+ gitlint --commits 725a2e4554bf9ba99e12adb1c77c3665d60d70fd..abde9d18038b88e43d9df5873ace0a260b00573f --config /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESVMEXAMPLESMANIFESTSTYLE12-CAMKESVMEXAMPLESMANIFESTGITLINTPR/standard_seL4_tools/misc/.gitlint
    02-Mar-2021 17:22:54	3: B6 Body message is missing
    02-Mar-2021 17:22:54	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-CAMKESVMEXAMPLESMANIFESTSTYLE12-CAMKESVMEXAMPLESMANIFESTGITLINTPR-1-ScriptBuildTask-5658520322308182873.sh] was 1 while expected 0
    02-Mar-2021 17:22:54	Finished task 'Lint commit messages' with result: Failed
    02-Mar-2021 17:22:54	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    02-Mar-2021 17:22:54	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESVMEXAMPLESMANIFESTSTYLE12-CAMKESVMEXAMPLESMANIFESTGITLINTPR
    02-Mar-2021 17:22:54	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    02-Mar-2021 17:22:54	Running post build plugin 'NCover Results Collector'
    02-Mar-2021 17:22:54	Running post build plugin 'Artifact Copier'
    02-Mar-2021 17:22:54	Running post build plugin 'npm Cache Cleanup'
    02-Mar-2021 17:22:54	Running post build plugin 'Clover Results Collector'
    02-Mar-2021 17:22:54	Running post build plugin 'Docker Container Cleanup'
    02-Mar-2021 17:22:54	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-CAMKESVMEXAMPLESMANIFESTSTYLE12-CAMKESVMEXAMPLESMANIFESTGITLINTPR'
    02-Mar-2021 17:22:54	Finalising the build...
    02-Mar-2021 17:22:54	Stopping timer.
    02-Mar-2021 17:22:54	Build CQ-CAMKESVMEXAMPLESMANIFESTSTYLE12-CAMKESVMEXAMPLESMANIFESTGITLINTPR-1 completed.
    02-Mar-2021 17:22:54	Running on server: post build plugin 'NCover Results Collector'
    02-Mar-2021 17:22:54	Running on server: post build plugin 'Build Hanging Detection Configuration'
    02-Mar-2021 17:22:54	Running on server: post build plugin 'Clover Delta Calculator'
    02-Mar-2021 17:22:54	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    02-Mar-2021 17:22:54	All post build plugins have finished
    02-Mar-2021 17:22:54	Generating build results summary...
    02-Mar-2021 17:22:54	Saving build results to disk...
    02-Mar-2021 17:22:54	Store variable context...
    02-Mar-2021 17:22:54	Indexing build results...
    02-Mar-2021 17:22:54	Finished building CQ-CAMKESVMEXAMPLESMANIFESTSTYLE12-CAMKESVMEXAMPLESMANIFESTGITLINTPR-1.


This is the most I can report on right now, sorry!

**Comment by oliver-wm** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by oliver-wm** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Review by xurtis — APPROVED** [review]

**Review by kent-mcleod — APPROVED** [review]

**Pull request closed without merging**
